project_name: gotestfmt
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/gotestfmt
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md
gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=example.com/blah
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
